package com.demo.po;

public class Color {
	
    @Override
	public String toString() {
		return "Color [id=" + id + ", name=" + name + ", parentId=" + parentId + ", imgUrl=" + imgUrl + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_color.id
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_color.name
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_color.parent_id
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_color.img_url
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_color.id
     *
     * @return the value of bbs_color.id
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_color.id
     *
     * @param id the value for bbs_color.id
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_color.name
     *
     * @return the value of bbs_color.name
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_color.name
     *
     * @param name the value for bbs_color.name
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_color.parent_id
     *
     * @return the value of bbs_color.parent_id
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_color.parent_id
     *
     * @param parentId the value for bbs_color.parent_id
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_color.img_url
     *
     * @return the value of bbs_color.img_url
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_color.img_url
     *
     * @param imgUrl the value for bbs_color.img_url
     *
     * @mbg.generated Mon Jun 24 16:01:01 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}